config/routes.rb
Rails.application.routes.draw do
  get 'welcome/home'

  resources :books

  resources :loans

  resources :readers

end

app/models/book.rb
class Book < ActiveRecord::Base
	has_many :loans
	belongs_to :loan

	validates :title, :presence => true
	validates :author, :presence => true
	validates :year, :numericality => { :only_integer => true }
end

app/models/loan.rb
class Loan < ActiveRecord::Base
	belongs_to :reader
	belongs_to :book

	has_many :books
end

app/models/reader.rb
class Reader < ActiveRecord::Base
	has_many :loans

	validates :name, :presence => true
	validates :phone, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
require 'digest/md5'
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate, except: [:index, :show]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :year, :image, :loan_id)
    end

  def authenticate
    authenticate_or_request_with_http_digest("localhost") do |username|
      if user = User.find_by_username(username)
        user.password
      else
        nil
      end
    end
  end
end

app/controllers/loans_controller.rb
require 'digest/md5'
class LoansController < ApplicationController
  before_action :set_loan, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate, except: [:index, :show]

  # GET /loans
  # GET /loans.json
  def index
    @loans = Loan.all
  end

  # GET /loans/1
  # GET /loans/1.json
  def show

  end

  # GET /loans/new
  def new
    @loan = Loan.new
  end

  # GET /loans/1/edit
  def edit
  end

  # POST /loans
  # POST /loans.json
  def create
    @loan = Loan.new(loan_params)

    respond_to do |format|
      if @loan.save
        format.html { redirect_to @loan, notice: 'Loan was successfully created.' }
        format.json { render :show, status: :created, location: @loan }
      else
        format.html { render :new }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loans/1
  # PATCH/PUT /loans/1.json
  def update
    respond_to do |format|
      if @loan.update(loan_params)
        format.html { redirect_to @loan, notice: 'Loan was successfully updated.' }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loans/1
  # DELETE /loans/1.json
  def destroy
    @loan.destroy
    respond_to do |format|
      format.html { redirect_to loans_url, notice: 'Loan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan
      @loan = Loan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loan_params
      params.require(:loan).permit(:date_loan, :date_return, :is_late, :penalty, :reader_id, :book_id)
    end

    def authenticate
    authenticate_or_request_with_http_digest("localhost") do |username|
      if user = User.find_by_username(username)
        user.password
      else
        nil
      end
    end
  end
end

app/controllers/readers_controller.rb
require 'digest/md5'
class ReadersController < ApplicationController
  before_action :set_reader, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate, except: [:index, :show]

  # GET /readers
  # GET /readers.json
  def index
    @readers = Reader.all
  end

  # GET /readers/1
  # GET /readers/1.json
  def show
  end

  # GET /readers/new
  def new
    @reader = Reader.new
  end

  # GET /readers/1/edit
  def edit
  end

  # POST /readers
  # POST /readers.json
  def create
    @reader = Reader.new(reader_params)

    respond_to do |format|
      if @reader.save
        format.html { redirect_to @reader, notice: 'Reader was successfully created.' }
        format.json { render :show, status: :created, location: @reader }
      else
        format.html { render :new }
        format.json { render json: @reader.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /readers/1
  # PATCH/PUT /readers/1.json
  def update
    respond_to do |format|
      if @reader.update(reader_params)
        format.html { redirect_to @reader, notice: 'Reader was successfully updated.' }
        format.json { render :show, status: :ok, location: @reader }
      else
        format.html { render :edit }
        format.json { render json: @reader.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /readers/1
  # DELETE /readers/1.json
  def destroy
    @reader.destroy
    respond_to do |format|
      format.html { redirect_to readers_url, notice: 'Reader was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reader
      @reader = Reader.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reader_params
      params.require(:reader).permit(:name, :phone, :address, :email)
    end

    def authenticate
    authenticate_or_request_with_http_digest("localhost") do |username|
      if user = User.find_by_username(username)
        user.password
      else
        nil
      end
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/readers_helper.rb
module ReadersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    Image file<br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :loan_id %><br>
    <%= f.number_field :loan_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="container">
	<h1 class="center">Edit book <%= @book.title %></h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>
</div>

app/views/books/index.html.erb
<div class="container">
<h1 class="center">All books available</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= image_tag book.image, width: '50px' %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>
</div>

app/views/books/new.html.erb
<div class="container">
<h1 class="center">Create a new book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>
</div>

app/views/books/show.html.erb
<div class="container">
  <h1 class="center">Details about <%= @book.title %> </h1>
<br>
  <p id="notice"><%= notice %></p>

  <div class="right" style="width:750px">
    <p>
      <strong>Title:</strong>
      <%= @book.title %>
    </p>

    <p>
      <strong>Author:</strong>
      <%= @book.author %>
    </p>

    <p>
      <strong>Year:</strong>
      <%= @book.year %>
    </p>

    <p>
      <strong>Loan number:</strong>
      <%= @book.loan_id %>
    </p>

    <%= link_to 'Edit', edit_book_path(@book) %> |
  <%= link_to 'Back', books_path %>

  </div>

  <div class="left" style="width:200px">
    <%= image_tag @book.image %>
  </div>

  <br style="clear:both"> 

  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Public Library Website</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>  
</head>
<body>

<div class="center"><a href="http://localhost:3000/welcome/home"><%= image_tag "logo.jpg", width: "300px" %></a></div><br>

<div class="nav">
	<ul>
		<li><%= link_to "Home", welcome_home_path %></li>
		<li><%= link_to "All books", books_path %></li>
		<li><%= link_to "Register", readers_path %></li>
		<li><%= link_to "Loans", loans_path %></li>
	</ul>
</div>


<%= yield %>


<div class="footer">
	<div class="container">
		<ul>
			<li><%= link_to "Home", welcome_home_path %> | </li>
			<li><%= link_to "All books", books_path %> |</li>
			<li><%= link_to "Register", readers_path %> |</li>
			<li><%= link_to "Loans", loans_path %></li>
		</ul>

		<br style="clear:both">

		<p style="padding-left:40px">IT231 - Fall 2014 - Final Project<br>
			Developed by: Cinthia Fukami</p>
	</div>
</div>

</body>
</html>

app/views/loans/_form.html.erb
<%= form_for(@loan) do |f| %>
  <% if @loan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@loan.errors.count, "error") %> prohibited this loan from being saved:</h2>

      <ul>
      <% @loan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
    Reader<br>

    <% options = Reader.all.collect do |r| %>
      <% [r.name, r.id] %>
    <% end %>
    <%= f.select :reader_id, options %>  

  </div>
  <div class="field">
    Book title<br>

    <% opt = Book.all.collect do |b| %>
      <% [b.title, b.id] %>
    <% end %>

    <%= f.select :book_id, opt %>
  </div>

  <div class="field">
    Date of loan<br>
    <%= f.date_select :date_loan %>
  </div>
  <div class="field">
    Date of return<br>
    <%= f.date_select :date_return %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/loans/edit.html.erb
<div class="container">
<h1 class="center">Edit loan</h1>

<%= render 'form' %>

<%= link_to 'Show', @loan %> |
<%= link_to 'Back', loans_path %>
</div>

app/views/loans/index.html.erb
<div class="container">
<h1 class="center">Listing loans</h1>

<table>
  <thead>
    <tr>
      <th>Reader's name</th>
      <th>Book rented</th>
      <th>Date of loan</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @loans.each do |loan| %>
      <tr>
        <td><%= loan.reader.name%></td>
        <td><%= loan.book.title %></td>
        <td><%= loan.date_loan %></td>
        <td><%= link_to 'Show', loan %></td>
        <td><%= link_to 'Edit', edit_loan_path(loan) %></td>
        <td><%= link_to 'Destroy', loan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Loan', new_loan_path %>
</div>

app/views/loans/new.html.erb
<div class="container">
<h1 class="center">Add new loan</h1>

<%= render 'form' %>

<%= link_to 'Back', loans_path %>
</div>

app/views/loans/show.html.erb
<div class="container">
<h1 class="center">Showing details of loan</h1>
<p id="notice"><%= notice %></p>

<p>
  <strong>Reader's name:</strong>
  <%= @loan.reader.name %>
</p>

<p>
  <strong>Book rented:</strong>
  <%= @loan.book.title %>
</p>

<p>
  <strong>Date of loan:</strong>
  <%= @loan.date_loan %>
</p>

<p>
  <strong>Date of return:</strong>
  <%= @loan.date_return %>
</p>




<%= link_to 'Edit', edit_loan_path(@loan) %> |
<%= link_to 'Back', loans_path %>

</div>

app/views/readers/_form.html.erb
<%= form_for(@reader) do |f| %>
  <% if @reader.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reader.errors.count, "error") %> prohibited this reader from being saved:</h2>

      <ul>
      <% @reader.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/readers/edit.html.erb
<div class="container">
<h1 class="center">Editing reader <%= @reader.name %></h1>

<%= render 'form' %>

<%= link_to 'Show', @reader %> |
<%= link_to 'Back', readers_path %>
</div>

app/views/readers/index.html.erb
<div class="container">
<h1  class="center">Listing all registered readers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @readers.each do |reader| %>
      <tr>
        <td><%= reader.name %></td>
        <td><%= reader.phone %></td>
        <td><%= reader.address %></td>
        <td><%= reader.email %></td>
        <td><%= link_to 'Show', reader %></td>
        <td><%= link_to 'Edit', edit_reader_path(reader) %></td>
        <td><%= link_to 'Destroy', reader, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reader', new_reader_path %>
</div>

app/views/readers/new.html.erb
<div class="container">
<h1 class="center">Register</h1>

<%= render 'form' %>

<%= link_to 'Back', readers_path %>
</div>

app/views/readers/show.html.erb
<div class="container">
<h1 class="center">Showing details about <%= @reader.name %></h1>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @reader.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @reader.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @reader.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @reader.email %>
</p>

<%= link_to 'Edit', edit_reader_path(@reader) %> |
<%= link_to 'Back', readers_path %>
</div>

app/views/welcome/home.html.erb
<div class="welcome">
	<div class="container">

		<div class="right"><%= image_tag 'library.jpg', width: '300px' %></div>
		<h1>Welcome to the public library website!</h1>
		<p style="width:700px; float:left">If you need to rent a book, this is the perfect place to you. 
			We have available millions of titles from famous authors and you can rent as many books as you want for free. On this new website, you can rent a book without having to go out of your home! Click on the "Register" navigation to start renting books, or click on the "All books" button on the navigation to see all books that we have available.	But attention: some books may not be available at that moment, so make sure to click on the "show" button of the desired book and see if the "Loan number" field is filled. We hope you enjoy! </p>				
		<br style="clear:both">
	</div>
</div>

<div class="container">

	<div class="col-left">
		<h2>Open hours:</h2>
<p>Monday:	9:00AM – 9:00PM<br>
Tuesday: 9:00AM – 9:00PM<br>
Wednesday: 9:00AM – 9:00PM<br>
Thursday: 9:00AM – 9:00PM<br>
Friday:	9:00AM – 5:00PM<br>
Saturday: 9:00AM – 5:00PM<br>
Sunday:	1:00PM – 5:00PM</p>

	</div>


	<div class="col-right">
		<h2>Location:</h2>
		<p>123 Main Street<br>
		Chicago, Illinois</p>

		<h2>Contact info:</h2>
		<p>Tel: 123-456-7890<br>
		Email: library@library.com</p>
	</div>
</div>